# Generated by Django 4.1.7 on 2023-02-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadvisorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urgentcontact',
            options={'verbose_name_plural': 'Urgent contacts'},
        ),
        migrations.RemoveField(
            model_name='urgentcontact',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='urgentcontact',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter a valid email address.', max_length=254, null=True, unique=True),
        ),
    ]
