# Generated by Django 4.1.7 on 2023-02-27 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('roadvisorapp', '0002_alter_urgentcontact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', unique=True),
        ),
        migrations.AlterField(
            model_name='urgentcontact',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='urgentcontact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
